import { access } from "node:fs/promises";
export const SOURCES={redFunnel:"https://www.redfunnel.co.uk/isle-of-wight-ferry/plan/timetables/service-status",wightlink:"https://www.wightlink.co.uk/plan-your-journey/service-status",hovertravel:"https://www.hovertravel.co.uk/about/service-status/"};
const tidy=v=>String(v||"").replace(/\s+/g," ").trim();
export function statusCode(v){const t=tidy(v).toLowerCase();if(/cancel|suspend|not running|withdrawn/.test(t))return"cancelled";if(/delay|disrupt|alter|limited|revised|late/.test(t))return"disrupted";if(/on time|running to timetable|normal service|good service/.test(t))return"good";return"unknown"}
const make=(id,operator,name,route,mode,message,url,advisories=[])=>{const cleanMessage=tidy(message)||"Live status unavailable";const seen=new Set();const uniqueAdvisories=advisories.filter(advisory=>{const title=tidy(advisory.title),detail=tidy(advisory.message);const key=`${title.toLowerCase()}\u0000${detail.toLowerCase()}`;if(seen.has(key))return false;seen.add(key);const serviceText=cleanMessage.toLowerCase(),advisoryText=detail.toLowerCase();return advisoryText&&serviceText!==advisoryText&&!serviceText.includes(advisoryText)});return{id,operator,name,route,mode,status:statusCode(cleanMessage),message:cleanMessage,advisories:uniqueAdvisories,source_url:url}};
const notice=(title,message)=>({title:tidy(title),message:tidy(message)});
const MONTHS=["january","february","march","april","may","june","july","august","september","october","november","december"];
function appliesToday(value,now,timezone){const groups=[...tidy(value).matchAll(/([\d,\s&]+)\s+(JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)\b/gi)];if(!groups.length)return true;const parts=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:timezone,day:"numeric",month:"long"}).formatToParts(now).map(x=>[x.type,x.value.toLowerCase()]));return groups.some(group=>group[2].toLowerCase()===parts.month&&(group[1].match(/\d+/g)||[]).map(Number).includes(Number(parts.day)))}
export function parseRedFunnel(text,url=SOURCES.redFunnel,overrides=[],now=new Date(),timezone="Europe/London"){const body=tidy(text);const published=(label,next)=>body.match(new RegExp(`${label}\\s*:?\\s*(.+?)(?=${next}|Live Ferry Tracker|From Southampton|$)`,"i"))?.[1]||"";const notices=(Array.isArray(overrides)?overrides:[overrides]).filter(Boolean);const relevant=pattern=>notices.find(item=>pattern.test(`${item.title} ${item.message}`)&&appliesToday(`${item.title} ${item.message}`,now,timezone));const vehicleOverride=relevant(/vehicle|east cowes/i),redJetOverride=relevant(/red jet|west cowes/i);const fallback="Good service — no current issues reported";return[make("red_funnel_vehicle","Red Funnel","Vehicle Ferry","Southampton ↔ East Cowes","vehicle",published("Vehicle Ferry Service Status","Red Jet Service Status")||(vehicleOverride?vehicleOverride.message:fallback),url,vehicleOverride?[notice(vehicleOverride.title,vehicleOverride.message)]:[]),make("red_jet","Red Funnel","Red Jet","Southampton ↔ West Cowes","foot_passenger",published("Red Jet Service Status","Live Ferry Tracker")||(redJetOverride?redJetOverride.message:fallback),url,redJetOverride?[notice(redJetOverride.title,redJetOverride.message)]:[])]}
export function parseWightlink(rows,sections=[],url=SOURCES.wightlink){const list=rows.map(r=>r.map(tidy));return[["wightlink_fastcat","FastCat","Portsmouth Harbour ↔ Ryde Pier Head","foot_passenger",/Portsmouth Harbour|Ryde/],["wightlink_fishbourne","Vehicle Ferry","Portsmouth ↔ Fishbourne","vehicle",/Fishbourne/],["wightlink_yarmouth","Vehicle Ferry","Lymington ↔ Yarmouth","vehicle",/Lymington|Yarmouth/]].map(([id,name,route,mode,re])=>{const messages=list.filter(r=>re.test(r[0]||"")).map(r=>r[3]).filter(Boolean);const advisories=sections.filter(x=>re.test(`${x.title} ${x.message}`)&&!/restricted passenger numbers/i.test(x.title)).map(x=>notice(x.title,x.message));return make(id,"Wightlink",name,route,mode,[...new Set(messages)].join(" · ")||"Live status unavailable — check Wightlink",url,advisories)})}
export function parseHovertravel(statusText,panelText="",url=SOURCES.hovertravel){const message=tidy(statusText)||"Live status unavailable — check Hovertravel";const advisory=statusCode(message)==="good"||!tidy(panelText)?[]:[notice("Hovertravel service update",panelText)];return make("hovertravel","Hovertravel","Hovercraft","Southsea ↔ Ryde","foot_passenger",message,url,advisory)}
async function chromiumPath(){for(const path of[process.env.CHROMIUM_PATH,"/usr/bin/chromium-browser","/usr/bin/chromium"].filter(Boolean)){try{await access(path);return path}catch{}}throw new Error("Chromium executable was not found")}
async function gotoWithRetry(page,url){let lastError;for(let attempt=1;attempt<=3;attempt+=1){try{await page.goto(url,{waitUntil:"domcontentloaded",timeout:60000});return}catch(error){lastError=error;if(attempt<3)await page.waitForTimeout(attempt*2000)}}throw lastError}
export async function collect({timezone="Europe/London"}={}){const{chromium}=await import("playwright-core");const browser=await chromium.launch({executablePath:await chromiumPath(),headless:true,args:["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-background-networking"]});const services=[],errors=[];try{const context=await browser.newContext({locale:"en-GB",timezoneId:timezone});const redPage=await context.newPage();try{await gotoWithRetry(redPage,SOURCES.redFunnel);await redPage.waitForTimeout(3000);const overrides=await redPage.locator("#service-table .override-message").evaluateAll(items=>items.map(element=>({title:element.querySelector("strong")?.innerText||"Red Funnel service advisory",message:element.innerText||""})));services.push(...parseRedFunnel(await redPage.locator("body").innerText(),SOURCES.redFunnel,overrides,new Date(),timezone))}catch(e){errors.push(`Red Funnel: ${e.message}`)}finally{await redPage.close()}const wightlinkPage=await context.newPage();try{await gotoWithRetry(wightlinkPage,SOURCES.wightlink);await wightlinkPage.waitForTimeout(5000);const rows=await wightlinkPage.locator("table tr").evaluateAll(items=>items.map(row=>[...row.querySelectorAll("th,td")].map(cell=>cell.textContent||"")));const sections=await wightlinkPage.locator("#travel-updates + div [data-accordion-component='AccordionItem']").evaluateAll(items=>items.map(item=>({title:item.querySelector("h3")?.textContent||"Service advisory",message:[...item.querySelectorAll("p")].map(p=>p.textContent||"").join(" ")})));services.push(...parseWightlink(rows,sections))}catch(e){errors.push(`Wightlink: ${e.message}`)}finally{await wightlinkPage.close()}const hoverPage=await context.newPage();try{await gotoWithRetry(hoverPage,SOURCES.hovertravel);await hoverPage.waitForTimeout(2500);const statusText=await hoverPage.locator(".service-status .status--text").first().innerText();const panelText=await hoverPage.locator(".service-status .service-status--panel p").first().textContent().catch(()=>"");services.push(parseHovertravel(statusText,panelText))}catch(e){errors.push(`Hovertravel: ${e.message}`)}finally{await hoverPage.close()}}finally{await browser.close()}if(!services.length)throw new Error(errors.join("; ")||"No ferry services extracted");return{schema_version:"1.0",updated_at:new Date().toISOString(),services,source_errors:errors}}
