import { access } from "node:fs/promises";
export const SOURCES={redFunnel:"https://www.redfunnel.co.uk/isle-of-wight-ferry/plan/timetables/service-status",wightlink:"https://www.wightlink.co.uk/plan-your-journey/service-status"};
const tidy=v=>String(v||"").replace(/\s+/g," ").trim();
export function statusCode(v){const t=tidy(v).toLowerCase();if(/cancel|suspend|not running|withdrawn/.test(t))return"cancelled";if(/delay|disrupt|alter|limited|revised|late/.test(t))return"disrupted";if(/on time|running to timetable|normal service|good service/.test(t))return"good";return"unknown"}
const make=(id,operator,name,route,mode,message,url,advisories=[])=>({id,operator,name,route,mode,status:statusCode(message),message:tidy(message)||"Live status unavailable",advisories,source_url:url});
const notice=(title,message)=>({title:tidy(title),message:tidy(message)});
export function parseRedFunnel(text,url=SOURCES.redFunnel){const body=tidy(text);const current=(label,next)=>body.match(new RegExp(`${label}\\s*:?\\s*(.+?)(?=${next}|Live Ferry Tracker|From Southampton|$)`,"i"))?.[1]||"Live status unavailable — check Red Funnel";const notices=(kind)=>[...body.matchAll(new RegExp(`${kind} (UPDATE|NOTICE|LIFTS?)\\s*:?\\s*(.+?)(?=VEHICLE FERRY|RED JET|Real-Time ferry service status|$)`,"gi"))].map(m=>notice(`${kind} ${m[1]}`,m[2]));return[make("red_funnel_vehicle","Red Funnel","Vehicle Ferry","Southampton ↔ East Cowes","vehicle",current("Vehicle Ferry Service Status","Red Jet Service Status"),url,notices("VEHICLE FERRY")),make("red_jet","Red Funnel","Red Jet","Southampton ↔ West Cowes","foot_passenger",current("Red Jet Service Status","Live Ferry Tracker"),url,notices("RED JET"))]}
export function parseWightlink(rows,sections=[],url=SOURCES.wightlink){const list=rows.map(r=>r.map(tidy));return[["wightlink_fastcat","FastCat","Portsmouth Harbour ↔ Ryde Pier Head","foot_passenger",/Portsmouth Harbour|Ryde/],["wightlink_fishbourne","Vehicle Ferry","Portsmouth ↔ Fishbourne","vehicle",/Fishbourne/],["wightlink_yarmouth","Vehicle Ferry","Lymington ↔ Yarmouth","vehicle",/Lymington|Yarmouth/]].map(([id,name,route,mode,re])=>{const messages=list.filter(r=>re.test(r[0]||"")).map(r=>r[3]).filter(Boolean);const advisories=sections.filter(x=>re.test(`${x.title} ${x.message}`)).map(x=>notice(x.title,x.message));return make(id,"Wightlink",name,route,mode,[...new Set(messages)].join(" · ")||"Live status unavailable — check Wightlink",url,advisories)})}
async function chromiumPath(){for(const path of[process.env.CHROMIUM_PATH,"/usr/bin/chromium-browser","/usr/bin/chromium"].filter(Boolean)){try{await access(path);return path}catch{}}throw new Error("Chromium executable was not found")}
async function gotoWithRetry(page,url){let lastError;for(let attempt=1;attempt<=3;attempt+=1){try{await page.goto(url,{waitUntil:"domcontentloaded",timeout:60000});return}catch(error){lastError=error;if(attempt<3)await page.waitForTimeout(attempt*2000)}}throw lastError}
export async function collect({timezone="Europe/London"}={}){const{chromium}=await import("playwright-core");const browser=await chromium.launch({executablePath:await chromiumPath(),headless:true,args:["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-background-networking"]});const services=[],errors=[];try{const context=await browser.newContext({locale:"en-GB",timezoneId:timezone});const redPage=await context.newPage();try{await gotoWithRetry(redPage,SOURCES.redFunnel);await redPage.waitForTimeout(3000);services.push(...parseRedFunnel(await redPage.locator("body").innerText()))}catch(e){errors.push(`Red Funnel: ${e.message}`)}finally{await redPage.close()}const wightlinkPage=await context.newPage();try{await gotoWithRetry(wightlinkPage,SOURCES.wightlink);await wightlinkPage.waitForTimeout(5000);const rows=await wightlinkPage.locator("table tr").evaluateAll(items=>items.map(row=>[...row.querySelectorAll("th,td")].map(cell=>cell.textContent||"")));const sections=await wightlinkPage.locator("h3").evaluateAll(headings=>headings.map(heading=>{let message="",node=heading.nextElementSibling;while(node&&!/^H[1-3]$/.test(node.tagName)){message+=` ${node.textContent||""}`;node=node.nextElementSibling}return{title:heading.textContent||"",message}}));services.push(...parseWightlink(rows,sections))}catch(e){errors.push(`Wightlink: ${e.message}`)}finally{await wightlinkPage.close()}}finally{await browser.close()}if(!services.length)throw new Error(errors.join("; ")||"No ferry services extracted");return{schema_version:"1.0",updated_at:new Date().toISOString(),services,source_errors:errors}}
